"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { KeyRound, Navigation, ShieldCheck, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

function LoginContent() {
  const router = useRouter();
  const search = useSearchParams();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [portalToken, setPortalToken] = useState("");
  const [mode, setMode] = useState<"login" | "register" | "reset">("login");
  const [notice, setNotice] = useState<string>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();
  const next = search.get("next") || "/admin";
  const signIn = async () => { setBusy(true); setError(undefined); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "same-origin", body: JSON.stringify({ email, password }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error || "Anmeldung fehlgeschlagen"); const me = await fetch("/api/auth/me", { credentials: "same-origin" }); const identity = me.ok ? await me.json() as { role?: string } : undefined; router.replace(identity?.role === "driver" ? "/driver" : next); } catch (caught) { setError(caught instanceof Error ? caught.message : "Anmeldung fehlgeschlagen"); } finally { setBusy(false); } };
  const submitAccess = async () => { setBusy(true); setError(undefined); setNotice(undefined); try { const endpoint = mode === "reset" ? "/api/auth/password-reset" : "/api/auth/register"; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(mode === "reset" ? { email } : { email, password }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error || "Der Vorgang konnte nicht abgeschlossen werden."); setNotice(mode === "reset" ? "Wenn ein Konto mit dieser Adresse existiert, wurde ein Link zum Zurücksetzen versendet." : "Registrierung gestartet. Bitte bestätige die E-Mail und lasse dich anschließend von einem Admin zu einer Organisation einladen."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Der Vorgang konnte nicht abgeschlossen werden."); } finally { setBusy(false); } };
  const resetForm = () => { setError(undefined); setNotice(undefined); };
  const title = mode === "login" ? "Anmelden" : mode === "register" ? "Konto registrieren" : "Passwort zurücksetzen";
  const description = mode === "login" ? "Für Administration und Fahrer mit dem persönlichen Zugang anmelden." : mode === "register" ? "Ein neues Konto erhält erst durch eine Einladung Zugriff auf eine Organisation." : "Wir senden dir einen einmalig nutzbaren Link an deine E-Mail-Adresse.";
  return <main className="grid min-h-screen place-items-center bg-[#f1f5f3] p-4"><section className="w-full max-w-md rounded-3xl bg-white p-7 shadow-xl"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-500 text-white"><Navigation className="h-5 w-5 rotate-45 fill-white" /></span><div><p className="text-sm font-extrabold">Automate<span className="text-brand-600">X</span> Route</p><p className="text-xs text-muted">Sicherer Arbeitsbereich</p></div></div><h1 className="mt-8 text-2xl font-extrabold text-ink">{title}</h1><p className="mt-2 text-sm leading-6 text-muted">{description}</p><div className="mt-6 grid gap-3"><Input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="E-Mail-Adresse" />{mode !== "reset" && <Input type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Passwort" />}{mode === "login" ? <Button onClick={() => void signIn()} disabled={busy || !email || !password} className="h-12 bg-navy hover:bg-navy/90"><KeyRound className="h-4 w-4" />{busy ? "Anmeldung…" : "Sicher anmelden"}</Button> : <Button onClick={() => void submitAccess()} disabled={busy || !email || (mode === "register" && password.length < 8)} className="h-12"><UserPlus className="h-4 w-4" />{busy ? "Wird verarbeitet…" : mode === "register" ? "Konto anlegen" : "Reset-Link senden"}</Button>}{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}{notice && <p role="status" className="rounded-xl bg-brand-50 p-3 text-xs font-bold text-brand-800">{notice}</p>}</div><div className="mt-4 flex flex-wrap gap-3 text-xs font-bold"><button className="text-brand-700 underline underline-offset-4" onClick={() => { setMode("reset"); resetForm(); }}>Passwort vergessen?</button><button className="text-brand-700 underline underline-offset-4" onClick={() => { setMode(mode === "register" ? "login" : "register"); resetForm(); }}>{mode === "register" ? "Zur Anmeldung" : "Konto registrieren"}</button></div><div className="mt-7 border-t border-line pt-5"><p className="text-sm font-extrabold">Kundenportal öffnen</p><p className="mt-1 text-xs leading-5 text-muted">Kunden nutzen ihren persönlichen, zeitlich begrenzten Terminlink.</p><div className="mt-3 flex gap-2"><Input value={portalToken} onChange={(event) => setPortalToken(event.target.value)} placeholder="Link-Code eingeben" /><Button variant="outline" disabled={!portalToken.trim()} onClick={() => router.push(`/p/${encodeURIComponent(portalToken.trim())}`)}><ShieldCheck className="h-4 w-4" />Öffnen</Button></div></div></section></main>;
}

export default function LoginPage() { return <Suspense fallback={<main className="grid min-h-screen place-items-center bg-[#f1f5f3] text-sm text-muted">Lade Anmeldung…</main>}><LoginContent /></Suspense>; }
