// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/fahrer" | "/admin/import" | "/admin/inbox" | "/admin/kpis" | "/admin/kunden" | "/admin/live" | "/admin/planung" | "/admin/settings" | "/admin/vorgaenge" | "/driver" | "/invite" | "/login" | "/p/[token]"
type AppRouteHandlerRoutes = "/api/ai/plan-command" | "/api/audit" | "/api/auth/accept-invite" | "/api/auth/demo" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/customers" | "/api/driver/events" | "/api/driver/reports" | "/api/driver/tours" | "/api/drivers" | "/api/geocode" | "/api/health" | "/api/imports" | "/api/imports/[id]" | "/api/integrations/gmail" | "/api/integrations/gmail/callback" | "/api/integrations/gmail/connect" | "/api/plans" | "/api/plans/[id]" | "/api/plans/[id]/publish" | "/api/portal/[token]" | "/api/routes/[id]" | "/api/state" | "/api/webhooks/email"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/driver"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/fahrer": {}
  "/admin/import": {}
  "/admin/inbox": {}
  "/admin/kpis": {}
  "/admin/kunden": {}
  "/admin/live": {}
  "/admin/planung": {}
  "/admin/settings": {}
  "/admin/vorgaenge": {}
  "/api/ai/plan-command": {}
  "/api/audit": {}
  "/api/auth/accept-invite": {}
  "/api/auth/demo": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/customers": {}
  "/api/driver/events": {}
  "/api/driver/reports": {}
  "/api/driver/tours": {}
  "/api/drivers": {}
  "/api/geocode": {}
  "/api/health": {}
  "/api/imports": {}
  "/api/imports/[id]": { "id": string; }
  "/api/integrations/gmail": {}
  "/api/integrations/gmail/callback": {}
  "/api/integrations/gmail/connect": {}
  "/api/plans": {}
  "/api/plans/[id]": { "id": string; }
  "/api/plans/[id]/publish": { "id": string; }
  "/api/portal/[token]": { "token": string; }
  "/api/routes/[id]": { "id": string; }
  "/api/state": {}
  "/api/webhooks/email": {}
  "/driver": {}
  "/invite": {}
  "/login": {}
  "/p/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/driver": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
