// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/fahrer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/fahrer">> = Specific
  const handler = {} as typeof import("../../app/admin/fahrer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/import">> = Specific
  const handler = {} as typeof import("../../app/admin/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inbox">> = Specific
  const handler = {} as typeof import("../../app/admin/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/kpis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kpis">> = Specific
  const handler = {} as typeof import("../../app/admin/kpis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/kunden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kunden">> = Specific
  const handler = {} as typeof import("../../app/admin/kunden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/live">> = Specific
  const handler = {} as typeof import("../../app/admin/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/planung/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/planung">> = Specific
  const handler = {} as typeof import("../../app/admin/planung/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/vorgaenge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vorgaenge">> = Specific
  const handler = {} as typeof import("../../app/admin/vorgaenge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/driver/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/driver">> = Specific
  const handler = {} as typeof import("../../app/driver/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite">> = Specific
  const handler = {} as typeof import("../../app/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/p/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p/[token]">> = Specific
  const handler = {} as typeof import("../../app/p/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/plan-command/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/plan-command">> = Specific
  const handler = {} as typeof import("../../app/api/ai/plan-command/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit">> = Specific
  const handler = {} as typeof import("../../app/api/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/accept-invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/accept-invite">> = Specific
  const handler = {} as typeof import("../../app/api/auth/accept-invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/demo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/demo">> = Specific
  const handler = {} as typeof import("../../app/api/auth/demo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers">> = Specific
  const handler = {} as typeof import("../../app/api/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/driver/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/driver/events">> = Specific
  const handler = {} as typeof import("../../app/api/driver/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/driver/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/driver/reports">> = Specific
  const handler = {} as typeof import("../../app/api/driver/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/driver/tours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/driver/tours">> = Specific
  const handler = {} as typeof import("../../app/api/driver/tours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/drivers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drivers">> = Specific
  const handler = {} as typeof import("../../app/api/drivers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geocode">> = Specific
  const handler = {} as typeof import("../../app/api/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/imports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/imports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/imports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports">> = Specific
  const handler = {} as typeof import("../../app/api/imports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/gmail/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/gmail/callback">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/gmail/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/gmail/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/gmail/connect">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/gmail/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/gmail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/gmail">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/gmail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plans/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plans/[id]/publish">> = Specific
  const handler = {} as typeof import("../../app/api/plans/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plans/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plans/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/plans/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plans">> = Specific
  const handler = {} as typeof import("../../app/api/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/portal/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/portal/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/routes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/routes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/state">> = Specific
  const handler = {} as typeof import("../../app/api/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/email">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/driver/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/driver">> = Specific
  const handler = {} as typeof import("../../app/driver/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
